#!/usr/bin/env python3
"""
Extract mailbox's PRODUCTION Categorize system prompt from the Go source into
prompt.py, so the benchmark tests the exact prompt the app ships rather than a
paraphrase. Re-run whenever internal/ai/assistant.go changes.

  python3 genprompt.py [path/to/mailbox]
"""
import os
import re
import sys

REPO = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/workspace/mailbox")
SRC = os.path.join(REPO, "internal/ai/assistant.go")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompt.py")

# Go double-quoted literal: handles \" and \\ escapes
LIT = re.compile(r'"((?:[^"\\]|\\.)*)"')


def unescape(s):
    return (s.replace('\\"', '"').replace("\\n", "\n")
             .replace("\\t", "\t").replace("\\\\", "\\"))


def grab_concat(lines, start):
    """Collect a Go `x := "a" + "b" + ...` chain starting at line index `start`."""
    parts, i = [], start
    while i < len(lines):
        raw = lines[i]
        code = raw.split("//")[0] if raw.lstrip().startswith("//") else raw
        if raw.lstrip().startswith("//"):
            i += 1
            continue
        for m in LIT.finditer(code):
            parts.append(unescape(m.group(1)))
        if not code.rstrip().endswith("+"):
            break
        i += 1
    return "".join(parts), i


def find_categories(lines):
    """EmailCategories = the canonical label list."""
    for i, l in enumerate(lines):
        if "var EmailCategories = []string{" in l:
            buf = ""
            j = i
            while j < len(lines) and "}" not in lines[j][lines[j].find("{") + 1:]:
                buf += lines[j]
                j += 1
            buf += lines[j]
            return [unescape(m.group(1)) for m in LIT.finditer(buf)]
    return []


def main():
    if not os.path.exists(SRC):
        sys.exit(f"not found: {SRC}\npass the repo path as an argument")
    lines = open(SRC, encoding="utf-8").read().splitlines()

    sys_prompt = None
    for i, l in enumerate(lines):
        if re.match(r"\s*system\s*:=\s*\"", l) and "classify emails" in l:
            sys_prompt, _ = grab_concat(lines, i)
            break
    if not sys_prompt:
        sys.exit("could not locate the Categorize system prompt in assistant.go")

    cats = find_categories(lines)
    if not cats:
        sys.exit("could not locate EmailCategories")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write('"""AUTO-GENERATED by genprompt.py from internal/ai/assistant.go.\n'
                 'Do not edit by hand -- re-run genprompt.py instead.\n"""\n\n')
        fh.write(f"EMAIL_CATEGORIES = {cats!r}\n\n")
        fh.write(f"CATEGORIZE_SYSTEM = {sys_prompt!r}\n")

    print(f"wrote {OUT}")
    print(f"  categories ({len(cats)}): {cats}")
    print(f"  system prompt: {len(sys_prompt)} chars")
    print(f"  starts: {sys_prompt[:70]!r}")
    print(f"  ends  : {sys_prompt[-70:]!r}")
    # sanity: every canonical label must appear in the prompt
    missing = [c for c in cats if c not in sys_prompt]
    print(f"  labels absent from prompt: {missing or 'none'}")


if __name__ == "__main__":
    main()
